version: "3.4"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  #  volumes:
  #    - elasticData:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_DATABSE=booksapi
      - MYSQL_ROOT_PASSWORD=agisnotamused
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
#    volumes:
#      - sqlData:/var/lib/mysql
    networks:
      - esnet
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:6.1.1
#    ports:
#      - 5601:5601
#    networks:
#      - esnet
#    depends_on:
#      - elasticsearch
#  webapp:
#    container_name: webapp
#    build:
#      context: .
#      dockerfile: ./frontend/Dockerfile
#    ports:
#      - 4200:4200
#      - 49153:49153
#    networks:
#      - esnet
#    depends_on:
#      - elasticsearch
#      - mysql

volumes:
#  elasticData:
#    driver: local
  sqlData:
    driver: local

networks:
  esnet:
