version: "3.4"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    networks:
      - esnet
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_DATABSE=booksapi
      - MYSQL_ROOT_PASSWORD=agisnotamused
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    networks:
      - esnet
  webapp:
    container_name: webapp
    build:
      context: ./frontend
    ports:
      - 4200:4200
      - 49153:49153
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - mysql
networks:
  esnet:
