version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      # path mapping host:container
      - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: ./docker_frontend/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/var/www/html/frontend


networks:
  esnet:
