version: "3.4"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  sql:
    container_name: sql
    image: mysql/mysql-docker:5.7.20
    ports:
      - 3306:3306
    volumes:
      - sqlData:/var/lib/mysql
    networks:
      - esnet
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: ./docker_webapp/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/var/www/html/frontend
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - sql

volumes:
  - elasticData
  - sqlData
networks:
  esnet:
