export const Filter = {
  category: [{name: 'Horror', type: 'category', selected: false},
    {name: 'Adventure Stories & Action', type: 'category', selected: false},
    {name: 'Fiction', type: 'category', selected: false},
    {name: 'Mystery & Thrillers', type: 'category', selected: false},
    {name: 'Science & Technology', type: 'category', selected: false},
    {name: 'Computers & Internet', type: 'category', selected: false},
    {name: 'Politics & History', type: 'category', selected: false},
    {name: 'Romance', type: 'category', selected: false},
    {name: 'Sports', type: 'category', selected: false}],
  delivery: [{name: 'Super Fast', type: 'delivery', selected: false},
    {name: 'Fast', type: 'delivery', selected: false},
    {name: 'Normal', type: 'delivery', selected: false}],
  format: [{name: 'Audiobook', type: 'format', selected: false},
    {name: 'Paperback', type: 'format', selected: false},
    {name: 'Hardcover', type: 'format', selected: false}],
  price: [{name: 0, type: 'price', selected: false},
    {name: 10, type: 'price', selected: false},
    {name: 20, type: 'price', selected: false},
    {name: 30, type: 'price', selected: false},
    {name: 40, type: 'price', selected: false},
    {name: 50, type: 'price', selected: false}]
};
